var stage1 = {
  backstory: "It was a nice windy afternoon.  After tending to the crops, you went over to the pig pen to feed your pigs.  Then the chickens, and the cows after that.  Suddenly you hear a scream come from up the road.  With a shotgun in hand, you walk up to a person on top of another person, who of which is screaming.  Upon a closer look, you realize that this “person” is eating the other and quickly push them off with the back of your gun.  You check on the person on the floor, but no response and the other that you pushed back starts to get up, looking dead with rotting flesh and blood across the body.  Soon the other reaches the same state.  After dealing with them you rush back to your house and overhear the radio you left on.  “Stay indoors.  A virus has broken out causing humans to feast on one another.  Wait until authorities arrive.”  Shocked, you sit down in your chair.  You have two options.  Because you live on a farm, you could wait out the outbreak and strengthen your home.  On the other hand, you have friends far off in the city.",
  question: "Will you stay at the farm and strengthen your home, or leave off to the city in hopes your friends are okay?",
  choice1: "Stay at the farm",
  choice2: "Leave to the city",}

var stage1_1 = {
  backstory: "You decided to take the safer option and wait it out.  It’s been a couple of days and no word from any news outlet.  You haven’t seen a single police vehicle either.  Now you decide to take it into your own hands and strengthen your house.  Months have passed by and in the meantime, you’ve managed to transform your house into a fortress.  An electric fence that surrounds the perimeter, plenty of food, water, and ammunition to sustain yourself for years to come.  Not to mention healthy animals and crops in the backyard.  A year goes by since the outbreak and while feeding bacon the pig, you hear a scream up the road.",
  question: "Do you head towards the scream?  It could be someone in need of help.  On the other hand, playing it safe has done well for you so far.",
  choice1: "Go towards the scream",
  choice2: "Stay inside and let it pass",}

var stage1_2 = {
  backstory: "It’s been a couple of hours since you left the farm.  You haven’t seen any of those zombies yet but your truck is running low on fuel.  Luckily, you’re approaching a small town that has a gas station.  You stop and start to refuel the truck.  Looking around you don’t see anyone, human or zombie.  It has only been a couple of hours, so maybe everyone is locked up.  Suddenly, *bang* *bang* *bang*, gunshots echo throughout the silent town.  It had to be from another human.",
  question: "Do you go towards the gunshots?  It very well could be someone in need of help.  Or do you wait for your truck to fill up so you can leave?",
  choice1: "Head to the sound of gunshots",
  choice2: "Stay put and fill up the truck",}

var stage1_1_1 = {
  backstory: "You walk up the road and with a quick shot, you take out the undead before it can reach the man lying on the ground.  He’s still panicking on the ground and only calms down after you reach out to him.  Confused, you ask what he is doing out here by himself.  He has nothing on him but a knife, and he looks like he hasn’t eaten in a while.  He says that he’s been moving from group to group, but always finds himself the last alive.  Fatigued, he asks if he can go back to your place to get better.  He promises that in 4 days at the most, he will be gone.",
  question: "Do you take him back to get bandaged up?",
  choice1: "Take him back to the farm",
  choice2: "Leave him where he lays",}

var stage1_1_2 = {
  backstory: "You have a good thing going.  You decide to stay quiet and wait until it passes over.  After a while, the screaming stops and you return to your semi-tranquil life of feeding animals, tending to crops, and taking out the occasional zombie.  About 5 years have passed since the outbreak started.  Even after all this time, supplies are still high and you aren’t worried about running out anytime soon.  However, you have started to notice an increase in zombies over the years.  While the electric fence can take out most of them, you find yourself needing help once in a while.  This leaves you with a decision.  You and the fence are holding out for now, but what will happen in the future when more zombies arrive?",
  question: "Do you choose to stay at your home and kill the few zombies the fence can't?  Or do you plan to move locations?",
  choice1: "Stay and defend the farm",
  choice2: "Pack up and leave the farm",}

var stage1_2_1 = {
  backstory: "It must be another human.  So you run towards the source.  After turning a corner, you see multiple zombies surrounding a woman.  She’s able to kill a few but is getting overrun.  You lend a hand and help to kill the rest of the undead.  She thanks you and tells you about a nearby group she is a part of.  You decide to join her and return to her group.  There are multiple people, a few adults with even a couple of kids.  Her friends thank you and have some small talk, but even more gunshots are heard, with a man running into the building soon after.  He says that he encountered a big hoard of zombies which are headed this way.",
  question: "Do you help to defend this place that holds all these people you just met?  Or do you sneak away and head back to your truck to continue the journey?",
  choice1: "Defend the hideout and its people",
  choice2: "Sneak away to your truck",}

var stage1_2_2 = {
  backstory: "You must stay focused.  Your friends are waiting for you in the city.  You fill up on gas and continue your journey to the city.  You have finally reached the city.  Though due to you leaving in a hurry, and the long trip, you are running out of supplies.  Just like that town, the city is empty of any life.  While driving down the roads, you see multiple stores.",
  question: "Do you take a quick stop to loot up on supplies?  Or do you head straight towards your friend's apartment?",
  choice1: "Take a quick stop to gather",
  choice2: "Go to the apartment",}

var ending1_1_1_1 = "Injured and afraid, you decided to take the man back to the farm.  He takes a shower.  Bandages are given to him to help him heal.  You even feed him.  He starts to look better after the first day but then starts to get sick again and you can’t figure out why.  The next day while making dinner, you hear him collapse upstairs.  As you go to open his door, he bursts through and lunges at you.  He had just turned moments ago.  As the struggle continues, you pull out your back pocket knife and give him a quick death.  You look at his ankle and see a bite mark.  Must have happened when you first met.  You look at your shoulder and also see a bite mark.  From your years of experience, you know that a bite transforms you in about 3 days.  So you release all the farm animals.  Finish up some tasks.  Cook the best meal you’ve had in your life.  And as the sun starts to set, you sit on your front porch rocking chair with a cigarette in one hand and a pistol in another.  Wanting to go out as a human and not a monster, you take smoke one last cigar. *bang*";

var ending1_1_1_2 = "He’s been the last survivor of multiple groups, and you can’t trust him.  You feel guilty, but you’ve given him a chance to live, but that is as much as you can do.  You take a different route making sure he doesn’t know where the farm is.  Years later, you are in your house, and someone false into one of your pitfalls.  They ask for help, and remembering that man years ago, decide to help this person.  Aid is given to them, a full meal, even clean hot water.  You’ve both ended up growing fond of each other and allow them into your life, after years of solitude.  You both are now old enough to have grandchildren but know you are getting to that age.  On this final day, you pick out each other’s clothing, have a grand feast, and finally get married.  You crush up all of your medication and pour it into glasses of wine which you both drink.  You get into the same be and close your eyes for the final time.  The apocalypse may have not been fun, but at least you met each other.";

var ending1_1_2_1 = "You’ve lived here since the start of the apocalypse, and you have no plans of moving anytime soon.  The farms kept you safe all this time, so now it's time to return the favor.  A few months go by without trouble.  The fence kills most but you deal with the remaining zombies.  However one day, the fence is not able to keep up.  On this day, more zombies than usual show up and damage the fence.  From this day on, more and more zombies appear until you can no longer keep up.  The fences get torn down, the crops are destroyed and all forms of exit are blocked.  Now it’s only a matter of time until the front door breaks open.  It’s been a good run.";

var ending1_1_2_2 = "You’ve lived here since the start of the apocalypse.  The farms kept you safe all this time, but with zombies only increasing, the fort is not gonna hold forever.  After a month, you have prepared enough.  You have plenty of supplies to last you for a while, and plenty of weapons too.  Sadly you cannot take your farm animals, but at least bacon the pig will be able to run free.  You have also prepared the farm for if you ever return as well.  You reminisce about the years you spent here but now look forward to the years you’ll spend on the move.";

var ending1_2_1_1 = "Your friends are in the city.  But you can’t just leave other people, let alone children, to fight for themselves.  You as well as some others board up the windows and use furniture to block the doors.  Multiple people are attacking the zombies at the front door.  Others are keeping zombies that fell through a window at bay.  But there are just too many.  Noticing the growing numbers, you run to the back where a small window was broken open, clear of zombies.  It was too small for any adult, but just enough for a child.  Lifting them one by one, the children escape to have a better chance than one in here.  One by one, you all get overrun by their sheer numbers and with no way out, you pray that your friends are at least safe out there.";

var ending1_2_1_2 = "You want to stay, but your friends take priority.  While everyone is boarding up the windows, you sneak out the back and make it to your truck.  Filled with gas, you exit the town before and zombies reach you.  After an hour, you finally reach the city only to see a hoard of zombies filling the streets.  With a city of that size, there had to be a couple thousand in downtown at the least.  Multiple buildings have fallen to the ground, and there is no hope of reaching your friend's apartment.  Not able to enter the city, you continue past it towards another town.  On a billboard, you see a message telling you to head to a location only you and your friends would know about.  With that, you continue your journey.";

var ending1_2_2_1 = "Running low on supplies, you decided to stop at a few stores to gather up supplies.  One grocery store has all the canned food and water you could ever need.  The corner gun store has plenty of ammunition to keep you safe.  You even drop by the gas station which allows you to fill up.  Though you lost track of time and now thousands of zombies are filling the streets.  Quickly, you get into your truck but all the streets are now filled.  Taking only a rifle and whatever was in your backpack, you run into the open alleyway, where zombies start to fill that too.  You climb up a ladder that leads to the roof just before it crashes down on the zombies below.  You are now on the roof with a rifle, a backpack, and thousands of zombies below.";

var ending1_2_2_2 = "Avoiding any distractions, you’ve made it to your friend’s apartment in the fastest way possible.  You park next to the building, with no zombies in sight.  Quietly, you make your way up the stairs while taking out any undead along the way.  You make it to the apartment and hear rumbling.  Are they fighting zombies?  You rush in gun pointed up, only to find them about to leave.  Happy as could be, you drop your gun and hug them as you begin to cry.  They said they heard of a military outpost that would take anyone in, so you all get back into your truck.  You exit the city before the streets flood with the undead, and you head towards your next destination.";
